drop function if exists public.crm_agent_move_lead(uuid, public.crm_lead_stage, jsonb);
drop function if exists public.crm_return_lead_to_ai(uuid, text);
drop function if exists public.crm_move_human_lead(uuid, public.crm_lead_stage, text);
drop function if exists public.crm_take_human_lead(uuid, text);
drop table if exists public.crm_tasks;
drop table if exists public.crm_notes;
drop table if exists public.crm_activities;
drop table if exists public.crm_leads;
drop table if exists public.crm_contacts;
drop table if exists public.crm_organization_members;
drop table if exists public.crm_organizations;
drop function if exists public.crm_touch_updated_at();
drop function if exists public.crm_can_operate_org(uuid);
drop function if exists public.crm_is_org_manager(uuid);
drop function if exists public.crm_is_org_member(uuid);
drop type if exists public.crm_actor_type;
drop type if exists public.crm_task_status;
drop type if exists public.crm_priority;
drop type if exists public.crm_lead_stage;
drop type if exists public.crm_authority;
drop type if exists public.crm_member_role;
